[package]
name = "teacolonies"
version = "0.1.0"
edition = "2021"

[dependencies]
nbt_rust = { git = "https://github.com/hollowness-inside/nbt-rust" }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
uuid = {version = "1.15.1", features = ["v5"]}
zip = "2.2.3"
